all:
	echo "nothing"

.PHONY: sort

sort:
	python sort_line.py -file ../data/poetry.csv -sort 作者,作品
	python sort_line.py -file ../data/book.csv -sort 作者,作品
	python sort_line.py -file ../data/mood.csv -sort 日期
