all:
	echo "nothing"

.PHONY: sort

sort:
	python3 sort_line.py --file=../data/poetry.csv --keys=作者,作品
	python3 sort_line.py --file=../data/book.csv --keys=作者,作品
	python3 sort_line.py --file=../data/mood.csv --keys=日期
	python3 sort_line.py --file=../data/internet.csv --keys=日期
	python3 sort_line.py --file=../data/video.csv --keys=作品
