all:
	echo "nothing"

.PHONY: sort

sort:
	python sort_line.py --file=../data/poetry.csv --keys=作者,作品
	python sort_line.py --file=../data/book.csv --keys=作者,作品
	python sort_line.py --file=../data/mood.csv --keys=日期

