
name: Index App

on:
  schedule:
    - cron: "05 19 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - uses: actions/setup-python@v1
      with:
        python-version: 3.9.7
        architecture: 'x64'
    - name: Generate New Readme
      run: |
        python main.py
    - name: Commit Files
      run: |
        git config --local user.email "youguanxinqing@qq.com"
        git config --local user.name "youguanxinqing(bot)"
        git commit -m "update index $(date +%Y-%m-%d)" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.INDEX_ACTION_TOKEN }}
